/* eslint-env mocha */

// tests for mochaExample
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const dirtyChai = require('dirty-chai');

mochaPlugin.chai.use(dirtyChai);
const { expect } = mochaPlugin.chai;
const wrapped = mochaPlugin.getWrapper('mochaExample', '../../../src/functions/mochaExample.js', 'mochaExample');
const AWS = require('aws-sdk-mock');
const AWS_SDK = require('aws-sdk');

AWS.setSDKInstance(AWS_SDK);

describe('mochaExample', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => wrapped.run({
    body: JSON.stringify({
      parameter: 'Some randome text to appear on the client side if the test went successfully',
    }),
  }).then((response) => {
    expect(response).to.not.be.empty();
  }));
});
