/* eslint-env mocha */
'use strict'

// tests for mochaExample
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin')
const dirtyChai = require('dirty-chai')
mochaPlugin.chai.use(dirtyChai)
const expect = mochaPlugin.chai.expect
let wrapped = mochaPlugin.getWrapper('mochaExample', '../../../src/functions/mochaExample.js', 'mochaExample')
let AWS = require('aws-sdk-mock')
let AWS_SDK = require('aws-sdk')
AWS.setSDKInstance(AWS_SDK)

describe('mochaExample', () => {
  before((done) => {
    done()
  })

  it('implement tests here', () => {
    return wrapped.run({
      body: JSON.stringify({
        parameter: 'Some randome text to appear on the client side if the test went successfully'
      })
    }).then((response) => {
      expect(response).to.not.be.empty()
    })
  })
})
